import Head from "next/head";
import Banner from "../components/Banner";
import BestSeller from "../components/BestSeller";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import GenderProduct from "../components/GenderProduct";
import Header from "../components/Header";
import HotProduct from "../components/HotProduct";
import MenuBrand from "../components/MenuBrand";
import NavBar from "../components/NavBar";
import Support from "../components/Support";

export default function Home() {
  return (
    <div className="bg-perfume_red-bg">
      <Head>
        <title>Phong&rsquo;s Perfume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <MenuBrand />

        <NavBar />

        <Banner />

        <BestSeller />

        <HotProduct />

        <GenderProduct />

        <Support />

        <Contact />

        <Footer />
      </main>
    </div>
  );
}
