import Head from "next/head";
import Header from "../components/Header";
import MenuBrand from "../components/MenuBrand";
import NavBar from "../components/NavBar";

export default function Home() {
  return (
    <div className="bg-perfume_red-bg">
      <Head>
        <title>Phong&rsquo;s Perfume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <MenuBrand />

        <NavBar />
      </main>
    </div>
  );
}
